version: 0.2

phases:
    
    build:
        commands:
            - echo "S3 Upload Beginning"
            - aws s3 sync / s3://testpocbucket/ --region us-east-1 --delete --acl public-read
            - echo "S3 Upload Complete"

    post_build:
        commands:
            - echo "Build complete"
           